### ISSUE TITLE
How do you do multi in RedisDB::Cluster?

### ISSUE THREAD

**Issue by theclapp** [trinitum/RedisDB#28]
Do you have any example code for this?

**Comment by trinitum** [comment]
I don't really do multi on redis cluster myself because of antirez/redis#2515, and at the moment there's no possibility to do this using RedisDB::Cluster. I can relatively easy add to RedisDB::Cluster a method that would return a RedisDB object for a given keyslot, and then you can perform multi/exec on this RedisDB object. This might not work if affected keyslots migrate to another master at some point during the process though.

**Comment by trinitum** [comment]
I released RedisDB 2.51 which includes `node_for_slot` and `node_for_keys` methods. Use one of them to get RedisDB object and then do multi on this object.

**Comment by theclapp** [comment]
Thanks!
